Plugin\OmisePaymentGateway\Entity\OmiseConfig:
    type: entity
    table: plg_omise_config
    repositoryClass: Plugin\OmisePaymentGateway\Repository\OmiseConfigRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: text
            nullable: false
            default: ''
        info:
            type: text
            nullable: false
            default: ''
        delete_flg:
            type: smallint
            nullable: false
            default: '0'
        create_date:
            type: datetime
            nullable: false
        update_date:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
