#プラグイン名
name: OmisePaymentGateway
#プラグインコード
code: OmisePaymentGateway
#バージョン
version: 0.1
#サービスプロバイダ
service:
    - OmiseServiceProvider
#イベント名
event: OmiseEvent
orm.path:
    - /Resource/doctrine
migration.path:
    - /Migration
