#プラグイン名
name: Omise決済プラグイン
#プラグインコード
code: OmisePaymentGateway
#バージョン
version: 0.1
#サービスプロバイダ
service:
    - OmiseServiceProvider
#イベント名
event: OmiseEvent
orm.path:
    - /Resource/doctrine
migration.path:
    - /Migration
const: 
    OMISE_PLUGIN_NAME: Omise決済プラグイン
    OMISE_COMPANY_NAME: Omise Co., Ltd.
    OMISE_URL: https://www.omise.co/
    OMISE_URL_JA: https://www.omise.co/?locale=ja
    